name: reviewdog
on: [pull_request]
jobs:
  setup-matrix:
    name: setup / matrix
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: find target module for golangci
        run: |
          echo "TARGET_MODULES=`find \`pwd\` | grep \"/go.mod\" | sed -e \"s/\/go.mod//\" `" >> $GITHUB_ENV
          echo `find \`pwd\` | grep \"/go.mod\" | sed -e \"s/\/go.mod//\" `

  golangci-lint:
    name: runner / golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: hoge
        run: echo ${{ env.TARGET_MODULES }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: set golangci.yml path into env
        run: echo "GOLANGCI_YML=`pwd`/golangci.yml" >> $GITHUB_ENV

      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          golangci_lint_flags: --config=${{ env.GOLANGCI_YML }} ./...
          workdir: src/module_a
