name: reviewdog
on: [pull_request]
jobs:
  golangci-lint:
    name: runner / golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: echo current dir
        run: |
          echo "GOLANGCI_PATH=`pwd`/golangci.yml" >> $GITHUB_ENV
#          CURRENT_PATH=`pwd`
#          echo ${CURRENT_PATH}
#          echo "GOLANGCI_PATH=${CURRENT_PATH}/golangci.yml" >> $GITHUB_ENV
#          echo ${GOLANGCI_PATH}
      - name: env check
        run: echo ${GOLANGCI_PATH}
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          golangci_lint_flags: --config=${{ env.GOLANGCI_PATH }} ./...
          workdir: src/module_a
